
Simulink.defineIntEnumType('eCATStateEnum', ... 
	{'none','init', 'preOp', 'boot', 'safeOp','op','error'}, ...
	[0;1;2;3;4;8;10], ... 
	'Description', 'eCAT State', ...
	'DefaultValue', 'init', ...
	'HeaderFile', 'eCATState.h', ...
	'DataScope', 'Exported', ...
	'AddClassNameToEnumNames', true, ...
	'StorageType', 'int32');

Simulink.defineIntEnumType('linmotStateEnum', ... 
	{'undefined', ...           % 0 - not a defined state
    'init',...                  % 1 - first valid state
    'readyToEnable', ...        % 2 - ready to enable motor
    'switchingOn', ...          % 3 - switching on
    'homing', ...               % 4 - homing motor
    'enabled', ...              % 5 - enabled, and ready to run
    'error'}, ...               % 6 - error
	0:6, ... 
	'Description', 'Linmot State', ...
	'DefaultValue', 'undefined', ...
	'HeaderFile', 'linmotState.h', ...
	'DataScope', 'Exported', ...
	'AddClassNameToEnumNames', true, ...
	'StorageType', 'int32');
