
Simulink.defineIntEnumType('eCATStateEnum', ... 
	{'none','init', 'preOp', 'boot', 'safeOp','op','error'}, ...
	[0;1;2;3;4;8;10], ... 
	'Description', 'eCAT State', ...
	'DefaultValue', 'init', ...
	'HeaderFile', 'eCATState.h', ...
	'DataScope', 'Exported', ...
	'AddClassNameToEnumNames', true, ...
	'StorageType', 'int32');

Simulink.defineIntEnumType('linmotStateEnum', ... 
	{'undefined', ...           % 0 - not a defined state
    'init',...                  % 1 - first valid state
    'settingCounter',...        % 2 - setting encoder counter
    'readyToEnable', ...        % 3 - ready to enable motor
    'switchingOn', ...          % 4 - switching on
    'homing', ...               % 5 - homing motor
    'settingHomePos',...        % 6 - latching home position
    'enabled', ...              % 7 - enabled, and ready to run
    'error',...                 % 8 - error
    'resettingError'}, ...      % 9 - resetting error
	0:9, ... 
	'Description', 'Linmot State', ...
	'DefaultValue', 'undefined', ...
	'HeaderFile', 'linmotState.h', ...
	'DataScope', 'Exported', ...
	'AddClassNameToEnumNames', true, ...
	'StorageType', 'int32');

Simulink.defineIntEnumType('modeEnum', ... 
	{'undefined', ...       % 0 - not a defined state
    'off', ...              % 1 - off
    'openLoop',...          % 2 - open loop
    'posCtrl', ...          % 3 - positon control
    'forceCtrl'}, ...       % 4 - force control
	0:4, ... 
	'Description', 'Operating mode', ...
	'DefaultValue', 'undefined', ...
	'HeaderFile', 'mode.h', ...
	'DataScope', 'Exported', ...
	'AddClassNameToEnumNames', true, ...
	'StorageType', 'int32');

% experiment control state
Simulink.defineIntEnumType('expCtrlStateEnum', ...
    {'undefined',...        % 0
    'init',...              % 1
    'idle',...              % 2
    'rampingUp',...         % 3
    'running',...           % 4
    'rampingDown'},...      % 5
     0:5, ... 
	'Description', 'Exp Ctrl State', ...
	'DefaultValue', 'undefined', ...
	'HeaderFile', 'expCtrlState.h', ...
	'DataScope', 'Exported', ...
	'AddClassNameToEnumNames', true, ...
	'StorageType', 'int32');
